encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("newForm", views.newForm, name="newForm"),
    path("random", views.random, name="random"),
    path("search", views.search, name="search")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('wiki/', include("wikiSearch.urls"))
]

wikiSearch/urls.py
from django.urls import path

from . import views


app_name = "wikiSearch"
urlpatterns = [
    path("<str:name>", views.index, name="index"),
    path("edit/<str:name>", views.edit, name="edit")
]

encyclopedia/models.py
from django.db import models

# Create your models here.

wikiSearch/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from . import util
from random import randrange, choice


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def newForm(request):
    if request.method == "GET":
        return render(request, "encyclopedia/newForm.html")
    elif request.method == "POST":
        form = request.POST
        title = form["title"]
        if title in util.list_entries():
            return render(request,"encyclopedia/newForm.html", {
                "error": "Value is already included in encyclopedia!"
            })
        else:
            util.save_entry(title, form["description"])
            return HttpResponseRedirect("wiki/" + title )

def random(request):
    filenames = util.list_entries()
    # rand_idx = randrange(len(filenames))
    # random_name = filenames[rand_idx]
    random_name = choice(filenames)
    return HttpResponseRedirect("wiki/" + random_name)

def search(request):
    form = request.POST
    if request.method == "POST":
        form = request.POST
        name = form["title"]
        # return render(request, "wiki/" + name)
        return HttpResponseRedirect("wiki/" + name)

wikiSearch/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from . import util
import random

error = False
def index(request, name):
    filename = util.list_entries()
    if name in filename:
        return render(request, "wikiSearch/index.html", {
            'name': name,
            'data': util.get_entry(name)
        })
    else:
        error=True
        return render(request, "wikiSearch/index.html", {
            'name':name,
            'error':error
        })
        
def edit(request, name):
    if request.method == "GET":
        filename = util.list_entries()
        if name in filename:
            return render(request, "wikiSearch/edit.html", {
                'name': name,
                'data': util.get_entry(name)
            })
    elif request.method == "POST":
        form = request.POST
        description = form["description"]
        util.save_entry(name, description)
        return HttpResponseRedirect("../" + name)

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href={% url 'wikiSearch:index' name=entry %}><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action={% url 'encyclopedia:search' %}  method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="title" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newForm' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newForm.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {% if error %}
        <h1>{{error}}</h1>
    {% endif %}
    <form action="{% url 'encyclopedia:newForm' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>New Entry</legend>
            <label for="title">Title:</label>
            <input type="text" name="title" required placeholder="Title"><br>
            <label for="description">Description:</label><br>
            <textarea type="text" name="description" required placeholder="Description" rows="4" cols="50"></textarea><br>
            <input type="submit">
        </fieldset>
    </form>
{% endblock %}

wikiSearch/templates/wikiSearch/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{name}}
{% endblock %}

{% block body %}
    {% with nam=name %}
        <form action={% url 'wikiSearch:edit' name=nam %} method="POST">
            {% csrf_token %}
            <label for="description">Description:</label><br>
            <textarea type="text" name="description" required placeholder="Description" rows="4" cols="70">{{data}}</textarea><br>
            <input type="submit" value="save">
        </form>
    {% endwith %}

{% endblock %}

wikiSearch/templates/wikiSearch/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{name}}</title>
  </head>
  <body>
    {% if error %}
        <p>Error 404 {{name}} Not Found</p>
    {% else %}
        {{ data }}
    {% endif %}
    <footer>
      {% with nam=name %}
        <a href={% url 'wikiSearch:edit' name=nam %}><button>Edit Entry</button></a>
      {% endwith %}
    </footer> 
  </body>   
</html>

wikiSearch/templates/wikiSearch/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action={% url 'wikiSearch:search' %}  method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="title" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newForm' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wikiSearch:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>